In [1]:
import os
project_name = "reco-tut-mll"; branch = "main"; account = "sparsh-ai"
project_path = os.path.join('/content', project_name)

In [2]:
if not os.path.exists(project_path):
    !cp /content/drive/MyDrive/mykeys.py /content
    import mykeys
    !rm /content/mykeys.py
    path = "/content/" + project_name; 
    !mkdir "{path}"
    %cd "{path}"
    import sys; sys.path.append(path)
    !git config --global user.email "recotut@recohut.com"
    !git config --global user.name  "reco-tut"
    !git init
    !git remote add origin https://"{mykeys.git_token}":x-oauth-basic@github.com/"{account}"/"{project_name}".git
    !git pull origin "{branch}"
    !git checkout main
else:
    %cd "{project_path}"

/content/reco-tut-mll
Initialized empty Git repository in /content/reco-tut-mll/.git/
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 29 (delta 6), reused 25 (delta 3), pack-reused 0
Unpacking objects: 100% (29/29), done.
From https://github.com/sparsh-ai/reco-tut-mll
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'

In [ ]:
!git status

In [ ]:
!git add . && git commit -m 'commit' && git push origin "{branch}"

---

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ratings = pd.read_parquet('./data/silver/ratings.parquet.gzip')
ratings.head()

   userId  movieId  rating           timestamp
0       1        1     4.0 2000-07-30 18:45:03
1     517        1     4.0 2017-02-24 16:39:03
2     213        1     3.5 2011-09-16 18:02:37
3     514        1     4.0 2018-08-10 03:40:00
4     214        1     3.0 1997-01-22 12:57:35

In [ ]:
movies = pd.read_parquet('./data/silver/movies.parquet.gzip')
movies.head()

   movieId                        title    year  ...  Thriller    War  Western
0        1                    Toy Story  1995.0  ...     False  False    False
1        2                      Jumanji  1995.0  ...     False  False    False
2        3             Grumpier Old Men  1995.0  ...     False  False    False
3        4            Waiting to Exhale  1995.0  ...     False  False    False
4        5  Father of the Bride Part II  1995.0  ...     False  False    False

[5 rows x 23 columns]

In [ ]:
movie_ratings = pd.merge(ratings, movies, on='movieId')
ratings = pd.DataFrame(movie_ratings.groupby('title')['rating'].mean())
ratings['No_of_ratings'] = pd.DataFrame(movie_ratings.groupby('title')['rating'].count())
ratings.sort_values(by=['No_of_ratings'], ascending=False).head()

                             rating  No_of_ratings
title
Forrest Gump               4.164134            329
Shawshank Redemption, The  4.429022            317
Pulp Fiction               4.197068            307
Silence of the Lambs, The  4.161290            279
Matrix, The                4.192446            278

In [ ]:
user_movie_matrix = movie_ratings.pivot_table(index='userId', columns='title', values='rating')
user_movie_matrix.iloc[:5,:5]

title   '71  'Hellboy': The Seeds of Creation  ...  'Salem's Lot  'Til There Was You
userId                                         ...
1       NaN                               NaN  ...           NaN                 NaN
2       NaN                               NaN  ...           NaN                 NaN
3       NaN                               NaN  ...           NaN                 NaN
4       NaN                               NaN  ...           NaN                 NaN
5       NaN                               NaN  ...           NaN                 NaN

[5 rows x 5 columns]

In [ ]:
matrix_movie_ratings = user_movie_matrix['Matrix, The']
matrix_movie_ratings.dropna(inplace=True)   # Remove users that have not given any rating
matrix_movie_ratings.head()

userId
1     5.0
4     1.0
10    0.5
13    5.0
15    4.0
Name: Matrix, The, dtype: float64

In [ ]:
# Retrieve all movies related to matrix
movies_like_the_matrix = user_movie_matrix.corrwith(matrix_movie_ratings)

# Create a DataFrame that contains movies and correlation
corr_the_matrix = pd.DataFrame(movies_like_the_matrix, columns=['Correlation'])

# Drop all NA values
corr_the_matrix.dropna(inplace=True)

In [ ]:
corr_the_matrix.head()

                         Correlation
title
'burbs, The                -0.160843
(500) Days of Summer        0.302316
*batteries not included     0.392232
...And Justice for All      0.654654
10 Cent Pistol             -1.000000

In [ ]:
corr_the_matrix = corr_the_matrix.join(ratings['No_of_ratings'])

# In order to increase confidence interval, only take movies with more than 20 ratings
corr_the_matrix = corr_the_matrix[corr_the_matrix['No_of_ratings'] > 20]

# R2 is the percentage of variation explained by the relationship between two variables
# In this case R2 shows the percentage of the relationship between two movies.
# Take the square of R which is the correlation
corr_the_matrix['R_Square'] = np.square(corr_the_matrix['Correlation']) 

# Show as Percantage
corr_the_matrix['Similarity'] = np.multiply(corr_the_matrix['R_Square'], 100)
corr_the_matrix['Similarity'] = np.multiply(corr_the_matrix['Similarity'], np.sign(corr_the_matrix['Correlation'])) 
similarity_df = pd.DataFrame(corr_the_matrix, columns=['Correlation', 'No_of_ratings', 'R_Square', 'Similarity'])
similarity_df['Similarity']= similarity_df['Similarity'].map('{:,.2f}%'.format)

In [ ]:
similarity_df.sort_values('Correlation', ascending=False).head(20)

                            Correlation  No_of_ratings  R_Square Similarity
title
Matrix, The                    1.000000            278  1.000000    100.00%
Wyatt Earp                     0.859338             21  0.738462     73.85%
Cabin in the Woods, The        0.795494             22  0.632811     63.28%
Shaft                          0.761658             22  0.580123     58.01%
Zootopia                       0.760610             32  0.578528     57.85%
Life of Pi                     0.710196             31  0.504379     50.44%
Milk Money                     0.704068             22  0.495712     49.57%
1408                           0.702785             25  0.493907     49.39%
X-Men: Days of Future Past     0.695681             30  0.483972     48.40%
Tarzan                         0.680988             24  0.463744     46.37%
Scent of a Woman               0.679637             27  0.461907     46.19%
2012                           0.675622             21  0.456465     45.65%
Tommy Boy                      0.674887             50  0.455473     45.55%
Tangled                        0.673630             24  0.453777     45.38%
Right Stuff, The               0.662497             22  0.438902     43.89%
Iron Man 3                     0.657786             32  0.432682     43.27%
Gravity                        0.648136             32  0.420080     42.01%
Finding Neverland              0.647576             32  0.419355     41.94%
Mickey Blue Eyes               0.646657             23  0.418165     41.82%
Forget Paris                   0.636285             22  0.404858     40.49%