In [ ]:
!pip install mars-gym

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from mars_gym.data import utils
utils.datasets()

['random',
 'yoochoose',
 'processed_yoochoose',
 'trivago_rio',
 'processed_trivago_rio']

In [4]:
df, df_meta = utils.load_dataset('processed_trivago_rio')
df.head()

3.55kKB [00:00, 31.4kKB/s]
605KB [00:00, 27.2kKB/s]

      session_id       user_id  ...  pos_item_id clicked
0  05fe82b496fb9  M1Z13DD0P2KH  ...            7     1.0
1  05fe82b496fb9  M1Z13DD0P2KH  ...           20     1.0
2  05fe82b496fb9  M1Z13DD0P2KH  ...            9     1.0
3  05fe82b496fb9  M1Z13DD0P2KH  ...           23     1.0
4  05fe82b496fb9  M1Z13DD0P2KH  ...           -1     0.0

[5 rows x 9 columns]

In [5]:
df_meta[['list_metadata']].head()

                                       list_metadata
0  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, ...
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2  [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, ...
3  [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, ...
4  [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, ...